=== api-evangelist/amazon-lookout-for-vision/json-schema/amazon-lookout-for-vision-greengrass-configuration-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-lookout-for-vision/refs/heads/main/json-schema/amazon-lookout-for-vision-greengrass-configuration-schema.json",
  "title": "GreengrassConfiguration",
  "description": "<p>Configuration information for the AWS IoT Greengrass component created in a model packaging job. For more information, see <a>StartModelPackagingJob</a>. </p> <note> <p>You can't specify a component with the same <code>ComponentName</code> and <code>Componentversion</code> as an existing component with the same component name and component version.</p> </note>",
  "type": "object",
  "properties": {
    "CompilerOptions": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CompilerOptions"
        },
        {
          "description": "<p>Additional compiler options for the Greengrass component. Currently, only NVIDIA Graphics Processing Units (GPU) and CPU accelerators are supported. If you specify <code>TargetDevice</code>, don't specify <code>CompilerOptions</code>.</p> <p>For more information, see <i>Compiler options</i> in the Amazon Lookout for Vision Developer Guide. </p>"
        }
      ]
    },
    "TargetDevice": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TargetDevice"
        },
        {
          "description": "The target device for the model. Currently the only supported value is <code>jetson_xavier</code>. If you specify <code>TargetDevice</code>, you can't specify <code>TargetPlatform</code>. "
        }
      ]
    },
    "TargetPlatform": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TargetPlatform"
        },
        {
          "description": "The target platform for the model. If you specify <code>TargetPlatform</code>, you can't specify <code>TargetDevice</code>. "
        }
      ]
    },
    "S3OutputLocation": {
      "allOf": [
        {
          "$ref": "#/components/schemas/S3Location"
        },
        {
          "description": " An S3 location in which Lookout for Vision stores the component artifacts. "
        }
      ]
    },
    "ComponentName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComponentName"
        },
        {
          "description": " A name for the AWS IoT Greengrass component. "
        }
      ]
    },
    "ComponentVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComponentVersion"
        },
        {
          "description": "A Version for the AWS IoT Greengrass component. If you don't provide a value, a default value of <code> <i>Model Version</i>.0.0</code> is used. "
        }
      ]
    },
    "ComponentDescription": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ComponentDescription"
        },
        {
          "description": " A description for the AWS IoT Greengrass component. "
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagList"
        },
        {
          "description": " A set of tags (key-value pairs) that you want to attach to the AWS IoT Greengrass component. "
        }
      ]
    }
  },
  "required": [
    "S3OutputLocation",
    "ComponentName"
  ]
}

=== api-evangelist/amazon-lookout-for-vision/examples/amazon-lookout-for-vision-greengrass-configuration-example.json
{
  "CompilerOptions": "example-value",
  "TargetDevice": "example-value",
  "TargetPlatform": "example-value",
  "S3OutputLocation": "example-value",
  "ComponentName": "my-project",
  "ComponentVersion": "1",
  "ComponentDescription": "Visual quality inspection model for manufacturing",
  "Tags": "example-value"
}
